name: Build MC Recon Tool

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Get app version
      id: get_version
      run: |
        $version = Select-String -Path MC_Recon_UI.py -Pattern "VERSION = '(.*)'"
        $version = $version.Matches.Groups[1].Value
        echo "APP_VERSION=$version" >> $env:GITHUB_ENV
        echo "App version: $version"

    - name: Build with PyInstaller
      run: |
        python build_with_version.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: recon_tools_v${{ env.APP_VERSION }}
        path: dist/MC对账明细工具_v${{ env.APP_VERSION }}.zip
