name: Build Windows Application

on:
  push:
    branches: [ main ]
    paths:
      - 'MC_Recon_UI.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'MC_Recon_UI.py'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build with PyInstaller
      run: |
        python build_with_version.py
    
    - name: Upload to DUFS
      run: |
        $file = Get-ChildItem "dist/MC_Recon_Tool_*.zip" | Select-Object -First 1
        curl -T $file.FullName -u fujiwen:Hilton1@# https://down.hksft.com/upload/
        
    - name: Get Updated App Version
      id: get_version
      run: |
        $version = Select-String -Path MC_Recon_UI.py -Pattern "VERSION = '([\d\.]+)'" | ForEach-Object { $_.Matches.Groups[1].Value }
        echo "APP_VERSION=$version" >> $env:GITHUB_ENV
        echo "Version detected: $version"
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: MC_Recon_Tool_v${{ env.APP_VERSION }}
        path: dist/*.exe
